services:
  reverse-proxy:
    hostname: reverse-proxy
    image: traefik:v3.1
    command: 
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entryPoints.http.address=:80
      - --entryPoints.http.forwardedHeaders.insecure
      - --log.level=WARN
      - --log.format=json
      - --accesslog=true
    networks:
      traefiknet:
        aliases:
          - auth.example.localhost
          - oauth.example.localhost
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefiknet:
    name: traefiknet
